---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@9a9a819da88d69f50842f77fdaa4fa103f5ca7cd # v1.38.3
    permissions:
      contents: read
      packages: read
      statuses: write
