---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@f44d7f8d2ae57bf084a30a36be11184e2f90321c # v1.34.3
    permissions:
      contents: read
      packages: read
      statuses: write
