---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@30c65c10c5d685575b7c475516b635f79bd128b5 # v1.39.0
    permissions:
      contents: read
      packages: read
      statuses: write
